name: ci
on:
  push:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      hivemq:
        image: hivemq/hivemq-ce:2023.9
        ports:
          - 1883:1883
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          MQTT_BROKER_URL: "tcp://localhost:1883"
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
